# Generated by Django 5.1 on 2024-08-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollmentID', models.IntegerField()),
                ('StudentID', models.IntegerField()),
                ('courename', models.CharField(max_length=30)),
                ('semester', models.CharField(max_length=20)),
            ],
        ),
    ]
